import { Metadata } from "next";
import SidebarProvider from "./__components/sidebar/sidebar-provider";

export const metadata: Metadata = {
  title: "School - Admin",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main className="bg-slate-100 flex min-h-screen">
      <SidebarProvider />
      <section className="flex-auto overflow-y-auto">{children}</section>
    </main>
  );
}
